apiVersion: v1
kind: Service # Service 정의 (API 서버에 대한 서비스)

metadata:
    name: numbers-api # 서비스 이름

spec:
  ports:
    - port: 80 # 서비스가 노출하는 포트
      targetPort: 80 # 컨테이너의 포트
      protocol: TCP # 프로토콜
  selector:
    app: numbers-api # 이 레이블을 가진 Pod을 선택
  type: ClusterIP # 서비스 타입 (ClusterIP는 클러스터 내부에서만 접근 가능 -> 웹 파드랑 통신해야하는 백엔드 파드에 주로 적합함)
