apiVersion: apps/v1
kind: Deployment # Deployment 정의

metadata: # Deployment 이름(메타데이터)
  name: sleep-1

spec:
  selector: # Label 셀렉터 정의
    matchLabels:
      app: sleep-1

  template:
    metadata:
      labels:
        app: sleep-1 # Pod 레이블 (Selector가 이 레이블을 가진 Pod을 선택함)

    spec:
      containers:
        - name: sleep
          image: kiamol/ch03-sleep