apiVersion: v1
kind: Service # Service 정의 (웹 서비스에 대한 서비스)

metadata:
  name: numbers-web # 서비스 이름

spec:
  ports:
    - protocol: TCP
      port: 8080 # 서비스가 노출하는 포트
      targetPort: 80 # 컨테이너가 사용하는 포트

  selector:
    app: numbers-web # 이 레이블을 가진 Pod을 선택해서 로드밸런싱

  type: LoadBalancer # 서비스 타입 (LoadBalancer는 외부에서 접근 가능 -> 웹 파드에 적합)
  